spring:
  application:
    name: releevante-api
  datasource:
    url: jdbc:postgresql://localhost:5432/relevantedb
    username: coex
    password: Summer01
    initialization-mode: always
    initialize: true
    continue-on-error: true
  sql:
    init:
      mode: never #always
      data-locations: classpath:identity_initial_data_insert.sql



  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
  webflux:
    base-path: /api
security:
  rsa:
    key-path:
      public: C:\\Users\\LEGION\Documents\\rsa\\public.pem
      private: C:\\Users\\LEGION\\Documents\\rsa\\private.pem

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    path: /swagger-ui.html
#  api-docs:
#    enabled: true
#    path: /api-docs
server:
  port: 8181







