services:
  flyway_server:
    image: flyway/flyway
    command: ${FLYWAY_COMMAND}
    volumes:
      # - ./flyway:/flyway/sql
      - ../backend-api/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
    networks:
      - releevante
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_SECRET}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - releevante
    restart: always
  backend-api:
    extends:
      file: ../backend-api/docker-compose.yml
      service: backend-api
    depends_on:
      - postgres
    networks:
      - releevante
  
  pgadmin:
    container_name: pgadmin_new
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-coex@commex.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - releevante
    restart: unless-stopped

networks:
  releevante:
    driver: bridge
    external: false
volumes:
    postgres:
    pgadmin: